spring:
  main:
    allow-circular-references: true
  application:
    name: journal App
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb+srv://username:dbpassword@cluster0.3xkkd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
  mail:
    host: smtp.gmail.com
    port: 587
    username: dmeo.tsting@gmail.com
    password: rwxc qlho bubo xyfa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    url: https://api.weatherstack.com/current?access_key=API_KEY&query=CITY
    key: 0e4bf6cdae49c98288c53b9dbd8a6761