spring:
  main:
    allow-circular-references: true
  application:
    name: journal App
  data:
    mongodb:
      auto-index-creation: true
      uri: XXXXXXXXXXXXXXXX
      database: journaldb
  mail:
    host: smtp.gmail.com
    port: 587
    username: email@gmail.com
    password: XXXXXXXXXX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

weather:
  api:
    url: https://api.weatherstack.com/current?access_key=API_KEY&query=CITY
    key: XXXXXXXXXXXXX
